# Generated by Django 4.2.4 on 2023-10-13 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalResources",
            new_name="HistoricalResource",
        ),
        migrations.RenameModel(
            old_name="Resources",
            new_name="Resource",
        ),
        migrations.AlterModelOptions(
            name="historicalresource",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical resource",
                "verbose_name_plural": "historical resources",
            },
        ),
    ]
