# Generated by Django 4.2.5 on 2023-11-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="resources",
            field=models.ManyToManyField(related_name="users", to="api.resource"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.DO_NOTHING, to="api.role"
            ),
        ),
    ]
