# Generated by Django 3.2 on 2023-08-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230824_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalresources',
            name='resource_group',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='resource_group',
        ),
        migrations.AddField(
            model_name='historicalresourcegroups',
            name='resources_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalresources',
            name='resource_groups_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcegroups',
            name='resources_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='resource_groups_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
