# Generated by Django 4.2.5 on 2023-11-10 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user_resources_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="role",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.DeleteModel(
            name="HistoricalRole",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
