# Generated by Django 4.2.4 on 2023-10-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_historicalresources_historicalresource_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="dependencies",
            field=models.ManyToManyField(related_name="jobs", to="api.dependency"),
        ),
        migrations.AlterField(
            model_name="assignmentrulecriteria",
            name="assignment_rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="api.assignmentrule",
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="dependency_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.dependencystatus",
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="dependency_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.dependencytypes"
            ),
        ),
    ]
