# Generated by Django 3.2 on 2023-10-10 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230927_0310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalJobs',
            new_name='HistoricalJob',
        ),
        migrations.AlterModelOptions(
            name='historicaljob',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical job', 'verbose_name_plural': 'historical jobs'},
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=250, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('planned_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('planned_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=150, null=True)),
                ('note', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job', to=settings.AUTH_USER_MODEL)),
                ('job_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.jobstatus')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.jobtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_job', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.AlterField(
            model_name='historicaljobdependency',
            name='job',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.job'),
        ),
        migrations.AlterField(
            model_name='historicaltasks',
            name='jobs',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.job'),
        ),
        migrations.AlterField(
            model_name='jobdependency',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.job'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_list', to='api.job'),
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['id', 'name'], name='job_id_08afe1_idx'),
        ),
    ]
