# Generated by Django 4.2.4 on 2023-10-15 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_job_dependencies_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltaskdependency",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicaltaskdependency",
            name="dependency",
        ),
        migrations.RemoveField(
            model_name="historicaltaskdependency",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaltaskdependency",
            name="task",
        ),
        migrations.RemoveField(
            model_name="historicaltaskdependency",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="jobdependency",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="jobdependency",
            name="dependency",
        ),
        migrations.RemoveField(
            model_name="jobdependency",
            name="job",
        ),
        migrations.RemoveField(
            model_name="jobdependency",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="taskdependency",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="taskdependency",
            name="dependency",
        ),
        migrations.RemoveField(
            model_name="taskdependency",
            name="task",
        ),
        migrations.RemoveField(
            model_name="taskdependency",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="HistoricalJobDependency",
        ),
        migrations.DeleteModel(
            name="HistoricalTaskDependency",
        ),
        migrations.DeleteModel(
            name="JobDependency",
        ),
        migrations.DeleteModel(
            name="TaskDependency",
        ),
    ]
