# Generated by Django 4.2.5 on 2023-11-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_customfield_historicalcustomfield_customfieldvalue_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentruleresourcegroup",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="assignmentruleresourcegroup",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="assignmentruleresourcegroup",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="assignmentruleresourcegroup",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="historicalassignmentruleresourcegroup",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="historicalassignmentruleresourcegroup",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalassignmentruleresourcegroup",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalassignmentruleresourcegroup",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="historicalassignmentruleresourcegroup",
            name="updated_by",
        ),
        migrations.AlterModelOptions(
            name="assignmentrule",
            options={"ordering": ("priority",)},
        ),
        migrations.RenameIndex(
            model_name="role",
            new_name="role_id_03930a_idx",
            old_name="roles_id_1c77ee_idx",
        ),
        migrations.RenameIndex(
            model_name="tasksresourceassignment",
            new_name="task_resour_id_227ee8_idx",
            old_name="tasks_resou_id_a203b5_idx",
        ),
        migrations.RemoveField(
            model_name="assignmentrule",
            name="resource_count",
        ),
        migrations.RemoveField(
            model_name="assignmentrule",
            name="use_all_resources",
        ),
        migrations.RemoveField(
            model_name="assignmentrulecriteria",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="customfieldvalue",
            name="value",
        ),
        migrations.RemoveField(
            model_name="historicalassignmentrule",
            name="resource_count",
        ),
        migrations.RemoveField(
            model_name="historicalassignmentrule",
            name="use_all_resources",
        ),
        migrations.RemoveField(
            model_name="historicalassignmentrulecriteria",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="historicaltasksresourceassignment",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="tasksresourceassignment",
            name="resource",
        ),
        migrations.AddField(
            model_name="assignmentrule",
            name="work_center",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.workcenter",
            ),
        ),
        migrations.AddField(
            model_name="historicalassignmentrule",
            name="work_center",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="api.workcenter",
            ),
        ),
        migrations.AddField(
            model_name="historicaltasksresourceassignment",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaltasksresourceassignment",
            name="resource_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaltasksresourceassignment",
            name="resource_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="api.resourcegroup",
            ),
        ),
        migrations.AddField(
            model_name="historicaltasksresourceassignment",
            name="use_all_resources",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tasksresourceassignment",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tasksresourceassignment",
            name="resource_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasksresourceassignment",
            name="resource_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_assignments",
                to="api.resourcegroup",
            ),
        ),
        migrations.AddField(
            model_name="tasksresourceassignment",
            name="resources",
            field=models.ManyToManyField(
                blank=True, related_name="task_assignments", to="api.resource"
            ),
        ),
        migrations.AddField(
            model_name="tasksresourceassignment",
            name="use_all_resources",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assignmentrule",
            name="priority",
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="assignmentrulecriteria",
            name="assignment_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="api.assignmentrule",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentrulecriteria",
            name="field",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="assignmentrulecriteria",
            name="operator",
            field=models.CharField(
                choices=[
                    ("equals", "Equals"),
                    ("contains", "Contains"),
                    ("starts_with", "Starts With"),
                    ("ends_with", "Ends With"),
                    ("gt", "Greater Than"),
                    ("lt", "Less Than"),
                ],
                default="equals",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalassignmentrule",
            name="priority",
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalassignmentrulecriteria",
            name="field",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalassignmentrulecriteria",
            name="operator",
            field=models.CharField(
                choices=[
                    ("equals", "Equals"),
                    ("contains", "Contains"),
                    ("starts_with", "Starts With"),
                    ("ends_with", "Ends With"),
                    ("gt", "Greater Than"),
                    ("lt", "Less Than"),
                ],
                default="equals",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tasksresourceassignment",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_assignments",
                to="api.task",
            ),
        ),
        migrations.AlterModelTable(
            name="historicalrole",
            table="role_history",
        ),
        migrations.AlterModelTable(
            name="historicaltasksresourceassignment",
            table="task_resource_assignment_history",
        ),
        migrations.AlterModelTable(
            name="role",
            table="role",
        ),
        migrations.AlterModelTable(
            name="tasksresourceassignment",
            table="task_resource_assignment",
        ),
        migrations.DeleteModel(
            name="AssignmentRuleResourceGroup",
        ),
        migrations.DeleteModel(
            name="HistoricalAssignmentRuleResourceGroup",
        ),
    ]
