# Generated by Django 4.2.6 on 2023-10-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customfield_historicalcustomfield_customfieldvalue_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customfield',
            name='custom_fiel_id_b33a4d_idx',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='label',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='style',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='validation',
        ),
        migrations.RemoveField(
            model_name='customfieldvalue',
            name='value',
        ),
        migrations.RemoveField(
            model_name='historicalcustomfield',
            name='label',
        ),
        migrations.RemoveField(
            model_name='historicalcustomfield',
            name='style',
        ),
        migrations.RemoveField(
            model_name='historicalcustomfield',
            name='validation',
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('datetime', 'DateTime'), ('time', 'Time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcustomfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('datetime', 'DateTime'), ('time', 'Time')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='customfield',
            index=models.Index(fields=['id', 'field_name', 'related_model'], name='custom_fiel_id_0ed23a_idx'),
        ),
    ]
