# Generated by Django 4.2.6 on 2023-10-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customfieldvalue_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvalue',
            name='custom_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='values', to='api.customfield'),
        ),
    ]
