# Generated by Django 4.2.4 on 2023-10-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_task_dependencies_alter_task_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalweeklyshifttemplate",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weeklyshifttemplate",
            name="details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="weekly_shift_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="resources",
                to="api.weeklyshifttemplate",
            ),
        ),
    ]
