# Generated by Django 4.2.5 on 2023-10-18 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user_role"),
        ("api", "0006_historicalweeklyshifttemplate_details_and_more"),
    ]

    operations = []
