# Generated by Django 4.2.6 on 2023-10-30 03:49

import api.models.custom_field_value
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customfieldvalue_custom_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='related_model',
        ),
        migrations.RemoveField(
            model_name='historicalcustomfield',
            name='related_model',
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='related_model',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[api.models.custom_field_value.validate_related_model]),
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together={('custom_field', 'object_id', 'related_model')},
        ),
    ]
