# Generated by Django 4.2.5 on 2023-10-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_merge_20231018_0415"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weeklyshifttemplatedetail",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="weeklyshifttemplatedetail",
            name="template",
        ),
        migrations.RemoveField(
            model_name="weeklyshifttemplatedetail",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="assignmentrulecriteria",
            name="assignment_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.assignmentrule",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalWeeklyShiftTemplateDetail",
        ),
        migrations.DeleteModel(
            name="WeeklyShiftTemplateDetail",
        ),
    ]
