# Generated by Django 3.2 on 2023-09-06 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230901_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('resource_count', models.IntegerField(blank=True, null=True)),
                ('use_all_resources', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'assignment_rule',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAssignmentRule',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('resource_count', models.IntegerField(blank=True, null=True)),
                ('use_all_resources', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical assignment rule',
                'verbose_name_plural': 'historical assignment rules',
                'db_table': 'assignment_rule_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTasksResourceAssignment',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical tasks resource assignment',
                'verbose_name_plural': 'historical tasks resource assignments',
                'db_table': 'tasks_resource_assignment_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TasksResourceAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tasks_resource_assignment',
            },
        ),
        migrations.RemoveIndex(
            model_name='dependencytypes',
            name='dependency__id_b3f5f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobs',
            name='jobs_id_dd826f_idx',
        ),
        migrations.RemoveIndex(
            model_name='resourcegroups',
            name='resource_gr_id_d4b4d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='resources',
            name='resources_id_c99ff5_idx',
        ),
        migrations.AddIndex(
            model_name='dependencytypes',
            index=models.Index(fields=['id', 'name'], name='dependency__id_ec0482_idx'),
        ),
        migrations.AddIndex(
            model_name='jobs',
            index=models.Index(fields=['id', 'name'], name='job_id_08afe1_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcegroups',
            index=models.Index(fields=['id', 'name'], name='resource_gr_id_61584f_idx'),
        ),
        migrations.AddIndex(
            model_name='resources',
            index=models.Index(fields=['id', 'name'], name='resource_id_9aa67b_idx'),
        ),
        migrations.AlterModelTable(
            name='dependencytypes',
            table='dependency_type',
        ),
        migrations.AlterModelTable(
            name='historicaldependencytypes',
            table='dependency_type_history',
        ),
        migrations.AlterModelTable(
            name='historicaljobs',
            table='job_history',
        ),
        migrations.AlterModelTable(
            name='historicalresourcegroups',
            table='resource_group_history',
        ),
        migrations.AlterModelTable(
            name='historicalresources',
            table='resource_history',
        ),
        migrations.AlterModelTable(
            name='jobs',
            table='job',
        ),
        migrations.AlterModelTable(
            name='resourcegroups',
            table='resource_group',
        ),
        migrations.AlterModelTable(
            name='resources',
            table='resource',
        ),
        migrations.AddField(
            model_name='tasksresourceassignment',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_assignment', to='api.resources'),
        ),
        migrations.AddField(
            model_name='tasksresourceassignment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignment', to='api.tasks'),
        ),
        migrations.AddField(
            model_name='historicaltasksresourceassignment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltasksresourceassignment',
            name='resource',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.resources'),
        ),
        migrations.AddField(
            model_name='historicaltasksresourceassignment',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.tasks'),
        ),
        migrations.AddField(
            model_name='historicalassignmentrule',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assignmentrule',
            index=models.Index(fields=['id', 'name'], name='assignment__id_47a262_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksresourceassignment',
            index=models.Index(fields=['id'], name='tasks_resou_id_a203b5_idx'),
        ),
    ]
