# Generated by Django 3.2 on 2023-09-08 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230906_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRuleCriteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=150)),
                ('operator', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('assignment_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.assignmentrule')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.assignmentrulecriteria')),
            ],
            options={
                'db_table': 'assignment_rule_criteria',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAssignmentRuleCriteria',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('field', models.CharField(max_length=150)),
                ('operator', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assignment_rule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.assignmentrule')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.assignmentrulecriteria')),
            ],
            options={
                'verbose_name': 'historical assignment rule criteria',
                'verbose_name_plural': 'historical assignment rule criterias',
                'db_table': 'assignment_rule_criteria_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='assignmentrulecriteria',
            index=models.Index(fields=['id', 'field'], name='assignment__id_513bb0_idx'),
        ),
    ]
