# Generated by Django 3.2 on 2023-09-12 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230911_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperationalexception',
            name='external_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicaloperationalexception',
            name='operational_exception_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.operationalexceptiontype'),
        ),
        migrations.AddField(
            model_name='historicaloperationalexception',
            name='weekly_shift_template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.weeklyshifttemplate'),
        ),
        migrations.AddField(
            model_name='operationalexception',
            name='external_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='operationalexception',
            name='operational_exception_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operational_exception_type', to='api.operationalexceptiontype'),
        ),
        migrations.AddField(
            model_name='operationalexception',
            name='weekly_shift_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.weeklyshifttemplate'),
        ),
    ]
