# Generated by Django 3.2 on 2023-09-12 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20230912_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloperationalexception',
            name='operational_exception_type',
        ),
        migrations.RemoveField(
            model_name='operationalexception',
            name='operational_exception_type',
        ),
    ]
