# Generated by Django 3.2 on 2023-09-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20230912_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaloperationalexception',
            old_name='exception_type',
            new_name='operational_exception_type',
        ),
        migrations.RenameField(
            model_name='operationalexception',
            old_name='exception_type',
            new_name='operational_exception_type',
        ),
    ]
